### ISSUE TITLE
Secure config

### ISSUE THREAD

**Issue by domwong** [m3o/dev#348]
TO DEFINE: What needs to be done to allow us to use config service for secrets?

**Comment by asim** [comment]
My take on this. We probably have to start by rewriting the go-micro/config interface to be simple Get/Set/Delete/Watch and key being a string that can be dotted rather than a variadic input as we expect now. Then taking secret as an option to Get/Set to encode/decode. 

Then config access becomes:

```
micro config set --secret mykey foo bar
micro config get --secret mykey foo
```

Format may vary. We could then save secrets locally `micro user config set secret ...`

And in future could offer a secrets service which stores keys on the platform so that services can pull keys from there or just provide a simpler way of setting secrets in config.

**Comment by domwong** [comment]
> And in future could offer a secrets service which stores keys on the platform so that services can pull keys from there or just provide a simpler way of setting secrets in config.

So I think this is really interesting answer about the difference between secrets and config in k8s https://stackoverflow.com/a/36925553

> The idea is that you should:
> - Use secrets for things which are actually secret like API keys, credentials, etc
> - Use config map for not-secret configuration data
> In the future there will likely be some differentiators for secrets like rotation or support for backing the secret API w/ HSMs, etc. In general we like intent-based APIs, and the intent is definitely different for secret data vs. plain old configs.

Which makes me think we should keep them separate.

**Comment by asim** [comment]
Cool. In which case I don't think it's something we should bake into micro since it's an additive thing rather than required. Sounds like m3o/secrets service needs to live and we move non essential things there.
