### ISSUE TITLE
Automatically deploy master branch of micro to staging env

### ISSUE THREAD

**Issue by domwong** [m3o/dev#380]
So we always have an up to date staging env.

Could this be the starting point of an m3o service that does gitops that we can offer to others? Register a service against a github repo and this gitops service will periodically poll (stretch goal setup webhooks) and deploy when it sees an update

**Comment by asim** [comment]
Potentially coincide with https://github.com/m3o/dev/issues/365 so that "platform" becomes the thing that deals with orchestration.

**Comment by ben-toogood** [comment]
Proposal: we implement this using a new platform/gitops service. 

```
# GitOps Service

GitOps is responsible for performing updates based on changes in git. The service is configured with a GitHub PAT, repo name and webhook URL. When it starts, it will register a webhook against the repo using the GitHub webhooks API for the given URL.

When a commit is added to master, the service will trigger an update of the micro services using the runtime. For example, when a commit is added to micro/micro, all the micro services (e.g. the router, registry) will be updated. This is intended to be used in a staging environment to enable continuous deployments.
```

**Comment by ben-toogood** [comment]
The only thing i'm yet to determine is how to best update the core micro services using the runtime (since these services don't exist within the runtime, e.g. if you do `micro logs -f store`, it will return an error).

**Comment by domwong** [comment]
I'd be interested to hear what strategy you come up with to determine what should be deployed and what shouldn't. I think this could be tricky to determine in an automated way because some repos may have multiple main.go but not all of them are services that should be run. Perhaps being explicit about telling the gitops service where the main.go is or something and pass an array of such locations to the gitops service.

Another thing to consider is how this will eventually interact with the future build service. Presumably, we listen for webhook, then ping the build service, then run the output of that. But for now I think just grabbing the source and running is ok

**Comment by ben-toogood** [comment]
Sorry I didn't explain this properly above. For the first version, I was planning to implement this for internal use only. e.g. it would use a repo loaded dynamically (we could configure staging to use one branch and master another), however it would loop through a hardcoded list (probably pulled from config) of services, much like we did with the status service.

I think having CD as an M3O feature would be amazing, however I'd implement this using a GitHub App so that it's easier to use for our users, and this would be completely separate. I built this previously and would like to re-implement it, but I think it falls outside the scope of this ticket.

**Comment by asim** [comment]
Let's please separate out the operations for services run on the platform vs the core runtime itself. If there is a "gitops" like service lets keep it to services on the platform. Core services should be updated via a different mechanism. Keep the two tickets and use cases separate.

**Comment by ben-toogood** [comment]
Okay, in that case I would propose:

• Update m3o/services using the proposed gitops service. We'll configure the gitops service to update all m3o/services in staging when there is a commit added to master.

• Update core (micro) services using a service similar to micro init. Now we have readiness checks etc it should work with zero downtime. I'd suggest naming the service "updater" and not starting it automatically with the server. To start the service you'd pass run the command "micro service updater".

**Comment by ben-toogood** [comment]
As per Asim's request, i'm going to scope this ticket to the micro updater service. @domwong I couldn't see a second ticket for auto-deploying m3o/services, i'll add one in backlog and leave it with you to prioritise.

**Comment by asim** [comment]
Works for me. We had this piece of code running on a server called "update" specifically designed to provide a place to poll for docker image updates since thats what we care about for core services, then it also included the git commit. We could essentially use this and some scheduling code that's smart about checking whats changed.

**Comment by ben-toogood** [comment]
Did you want this to be intelligent enough to only update based on what has changed between the latest ref and the one the service is running?

**Comment by asim** [comment]
Yes because having seen what happens when stuff restarts quite frequently it would be nice to avoid doing it unless we really have to. It means whatever this code is needs to have a slightly more intuitive understanding of Micro but maybe thats a good thing.

Design with the idea in mind that in the future all micro servers would periodically poll for updates and alert a user to a new version or change which could allow them to update the binary or self update. It might be easy enough for us to just run an update-service in m3o/services which everything can call to check at api.m3o.com/update
