### ISSUE TITLE
Compile binaries as service name

### ISSUE THREAD

**Issue by asim** [m3o/dev#504]
Go binaries locally appear as `/tmp/go-build929817807/b001/exe/main` in ps output. So assuming we still just go run. Build the binary as the [service-version] and execute so at the very least ps and top are useful.

**Comment by ben-toogood** [comment]
Locally when I test this I get an output which contains the service name. I tested this with a service in a mono-repo and a service at the top level and go the same result so i'm closing the card. 
```
17555 ttys000    0:01.38 /usr/local/Cellar/go/1.14.7/libexec/pkg/tool/darwin_amd64/link -o /var/folders/mk/1327yr6x5qlc6tfbdpr68kpw0000gq/T/go-build914961152/b001/exe/helloworld 
```

**Comment by ben-toogood** [comment]
I did look at adding a version to the path however it would require a change to the way we're doing args / commands as options (since we'd stop doing "go", "run", "." and end up doing two commands one build and one run. I don't believe the added complexity / having to ignore the options is worth the trade off. Please let me know if you'd like me to revisit.

**Comment by asim** [comment]
Please do not close until we can verify this is the case beyond mac OS.

**Comment by asim** [comment]
Ok looks like I'm getting the right output for the binary on linux. Might be an old version of micro it was not the case.
